### ISSUE TITLE
Mark homework 1, exercise 1 and 2 of Guanyu-Nie

### ISSUE THREAD

**Issue by guanyunie** [guanyunie/stat679work#1]
@cecileane
https://github.com/guanyunie/stat679work/commit/53170f973b3ae1533a9534d4065ad2bd89e7fb3a
# Instructions
## Files
- Working directory:hw1
- hw1-snaqTimeTests/
  - log/
  - out/
- scrips/
  - normalizeFileNames.sh
  - summaryizeSNaQres.sh
  - undoNormalizeFileNames.sh
- results/
  - summary.csv
- readme.md
## normalizeFileNames.sh

Exercise 1
Create a shell script `normalizeFileNames.sh` to change all file names `timetesty_snaq.log` to `timetest0y_snaq.log` where "y" is a digit between 1 and 9. Similarly, change `timetesty_snaq.out` to
`timetest0y_snaq.out`.
Code:

``` shell
for i in {1..9}
do
    mv hw1-snaqTimeTests/log/timetest${i}_snaq.log hw1-snaqTimeTests/log/timetest0${i}_snaq.log
    mv hw1-snaqTimeTests/out/timetest${i}_snaq.out hw1-snaqTimeTests/out/timetest0${i}_snaq.out
 done
```
## summaryizeSnaQres.sh

 Exercise 2
Start a summary of the results from all these analyses. The script produces a table in `csv` format,
with 1 row per analysis and 3 columns:
- "analysis": the file name root ("xxx")
- "h": the maximum number of hybridizations allowed during the analysis: `hmax`
- "CPUtime": total CPU time, or "Elapsed time".  
  Code:

``` shell
echo analysis, h, CPUtime > ../result/summary.csv

for file in ../hw1-snaqTimeTests/log/*.log
do
  analysis=`grep rootname $file | cut -f 2 -d ":"`

  outname="${file%.*}.out"
  outname="../hw1-snaqTimeTests/out/${outname##*/}"

  h=`grep hmax $file | head -n 1 | cut -f 2 -d '=' | cut -f1 -d,`

  CPUtime=`grep Elapsed\ time $outname | cut -f 2 -d ":"`
  CPUtime=${CPUtime% seconds*}

  echo $analysis, $h, $CPUtime >> ../result/summary.csv

done
```
## undoNormalizeFileNames.sh

``` shell
for i in {1..9}
do
  mv hw1-snaqTimeTests/log/timetest0${i}_snaq.log hw1-snaqTimeTests/log/timetest${i}_snaq.log
  mv hw1-snaqTimeTests/out/timetest0${i}_snaq.out hw1-snaqTimeTests/out/timetest${i}_snaq.out
done
```

**Comment by cecileane** [comment]
Hi Guanyu,

Great work! Your files are well organized, and you even have a script to "undo" the normalization script. Very nice! You are also making great use of the markdown syntax.

I had no problem running your normalization script, but I first had an error with the summarizing script. I ran it from the `hw1` directory, like the other script. I had to look at the code to figure our that it assumed I was in `hw1-snaqTimeTests` instead. Then it worked just fine.

The final file `result/summary.csv` should not have spaces. Commas are used to separate the columns, so spaces should not be added on top.

You have a clever use of `cut` with various delimiters, and several different uses of parameter expansion. You learned a lot there. Unfortunately, you did not get much practice with `grep` as a result, and of _extended_ regular expressions. Learning to use extended regular expressions would be useful for all other languages, not just the shell. Later, it will be best to use `sed` instead of parameter expansion, because `sed` is more versatile (even just to do search/replace).

final note: you are tracking a `.DS_Store` file in pretty much every directory... not good. Use `git status` more often to check what's (not) tracked, what was added, what would be committed.

Please close this issue, or [assign](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/) it to me and I can close it.
