### ISSUE TITLE
Mark homework 1, exercise 3 of Guanyu Nie

### ISSUE THREAD

**Issue by guanyunie** [guanyunie/stat679work#2]
Dear Professor  @cecileane ,
Here is my exercise 3 and the last commit is 33b9c02.
### Three files are updated:
- hw1/readme.md
- hw1/scripts/summaryizeSNaQres.sh
- results/summary.csv
### What I did:

Add more information about each analysis to summary.csv.

**Comment by cecileane** [comment]
Thanks Guanyu! This is my way of asking Cora (@coraallencoleman) and Xuchun (@xuchun725) to try your script and provide feedback on it.

**Comment by guanyunie** [comment]
Dear professor,

Sorry I didn’t fully understand you in class. What should I do about this? Do I also need to see two of my classmates’ script and provide feedback?

Guanyu

发件人: Cécile Ané notifications@github.com
答复: guanyunie/stat679work reply@reply.github.com
日期: 2016年10月13日 星期四 17:43
至: guanyunie/stat679work stat679work@noreply.github.com
抄送: Guanyu Nie gnie2@wisc.edu, Author author@noreply.github.com
主题: Re: [guanyunie/stat679work] Mark homework 1, exercise 3 of Guanyu Nie (#2)

Thanks Guanyu! This is my way of asking Cora (@coraallencolemanhttps://github.com/coraallencoleman) and Xuchun (@xuchun725https://github.com/xuchun725) to try your script and provide feedback on it.

**Comment by cecileane** [comment]
Hi Guanyu: you don't need to do anything. Your repo is public, so Cora and Xuchun should have received an email. They will look at your repository as if they were collaborators or users of your code, clone it, run it, see what you have done differently, and provide feedback on what they liked, what they learned, and what could have been better!

You should also look at the work from 2 of your classmates. If their repo is public, you should have received an email. If their repo is private, I've asked them to add you as collaborator. When they will do it, you will receive an email (you will need to accept their invitation), and their github issue will appear in your list of github issues.

**Comment by coraallensavietta** [comment]
Dear Guanyu,

Nice work! I like the way you organized your code into one loop with nested sub-loops. It's clear, lean, and full of clever ideas!

My first suggestion would be about the files your script includes. Right now, it runs not only on the timetest files, but also on bT1, net1, and newtry1 files. If you narrow the search in your opening statement, "for file in ../hw1-snaqTimeTests/log/*.log" to include only timetest files using something like, "for file in timetest". 

There is some misordering in your summary.csv (timetest10 listed before timetest01). I think this might be solved by running your normalizeFileNames.sh script before running the summarizeSNaQres.sh script.

I appreciated your detailed documentation within the script. It made it much easier to read! To make your code even clearer, it would be great to add documentation and notes at the top of the file about which files the script works on, where it should be run, and what it produces. 

The way you navigate between your scripts, results, and data directories was smart! I look forward to implementing this idea in my own future projects. I also liked your use of the concepts we've learned in class so far: loops,if-then statement, basename, grep, and sed. 

Thank you for sharing your work! It was a pleasure to learn from your code.

Best,
Cora

**Comment by cecileane** [comment]
Hi all, 
It's good actually, that Guanyu's script runs on all the analysis files: including `bT1`, `net1_snaq` etc. These data are messy, like almost all real data sets... I am sorry that the description didn't clarify what data files to include or not.

**Comment by xuchun725** [comment]
Hi Guanyu,  

Your code for ex3 runs well and the gets what you intended to get. But in your `summary.csv` file, there should be **no extra space** after each comma since comma is the delimiter for `csv` ("comma-separated values") file.

You have a smart use of `basename`, `grep`, `cut`, `sed`, _extended regular expression_, `for` loop, `if` statement, _arithmetic expansion_ and _parameter expansion_. The comments make it clear for each step and easy to follow. But I think adding some instruction on the top of `.sh` file may make it easy for your collaborators and even yourself (in the future) to understand what this script for, how and where to run it and what result you can get. As for the variables you used, I understand `$file` is filename in `log/`, `$outname` is filename in `out/`, but the format is not very consistent. Maybe `$logname` and `$outname` are better. Or probably `${basename}.log` and `${basename}.out`.

I love how your files are organized. Scripts, results and data are stored in separate directories. I will do this to improve my documentation in further projects. The `readme.md` file with a lot of markdown style is really human-readable. But it seems you forgot to add a tag `v1.2` for the final version of hw1 ex1&2.

Overall, it's a great work!

Best, 
Xuchun
