### ISSUE TITLE
Mark homework 2 of Guanyu Nie

### ISSUE THREAD

**Issue by guanyunie** [guanyunie/stat679work#3]
Dear Professor @cecileane ,
Here is my homework 2 and the last commit is c075977.

Usage:

```shell
IPython
import compare_date
import merging
merging.merging("waterTemperature.csv","energy.csv")
```

Thank you,
Guanyu Nie

**Comment by guanyunie** [comment]
readme.md updated.  New commit: 49c0d1e

**Comment by cecileane** [comment]
Hi Guanyu,
Very nice job! More details below.

## overall presentation

I had trouble with your git repository. Did you "force" push one or more commits at some point? Or did you "rebase" with git at some point? This is something to avoid, for any commit that has been pushed and that someone has used already.

In general, it's good to get into the habit of separating the scripts and input/output files into different directories.
It's too bad that I could not run your script from the shell, and pass it the file names through arguments in the shell.

You made good use of markdown style in your readme file.

## running your script

Your github issue message had instructions that your readme file didn't have, like this:

```python
import compare_date
import merging
merging.merging("waterTemperature.csv","energy.csv")
```

It would have been more user-friendly to have placed both functions in the same file. That way, the user only has to import one file. It would also have been great if you could have used the argparse module. For example, if I gave the file names in the wrong order, the error message that I got was not helpful (using the argparse module would have helped for better error messages:)

```python
>>> import merging as m
>>> m.merging("energy.csv", "waterTemperature.csv")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ane/Documents/private/st679/studenthw/guanyuNie/hw2/merging.py", line 26, in merging
    currentEnergyDay = energyDate[n_energy-1]
IndexError: list index out of range
>>> m.merging("waterTemperature.csv", "energy.csv")
>>> quit()
```

After that, I discovered that `output.csv` had been recently changed. Using the argparse module would have helped to let the user choose its output file name.

Unfortunately, your output is missing a comma at the end of each line that does not have an energy value. A comma should be there to signify that there is another column, with a missing value in it. GitHub is not happy with this missing comma either, see [here](https://github.com/guanyunie/stat679work/blob/master/hw2/output.csv). Your output was like this:

    #,"Date Time, GMT-05:00","K-Type, °F (LGR S/N: 10679014, SEN S/N: 10679014, LBL: water pipe)",energy
    1,07/29/16 10:26:34 AM,72.86
    2,07/29/16 11:26:34 AM,73.92
    3,07/29/16 12:26:34 PM,73.98
    ...
    13,07/29/16 10:26:34 PM,73.27
    14,07/29/16 11:26:34 PM,73.45,9.468
    15,07/30/16 12:26:34 AM,72.30

instead of this (see the extra commas so that all rows have 4 columns):

    #,"Date Time, GMT-05:00","K-Type, °F (LGR S/N: 10679014, SEN S/N: 10679014, LBL: water pipe)",energy
    1,07/29/16 10:26:34 AM,72.86,
    2,07/29/16 11:26:34 AM,73.92,
    3,07/29/16 12:26:34 PM,73.98,
    ...
    13,07/29/16 10:26:34 PM,73.27,
    14,07/29/16 11:26:34 PM,73.45,9.468
    15,07/30/16 12:26:34 AM,72.30,

## about your code

Your function to compare dates is thorough and you made great use of regular expressions: great job!

Your code would benefit from being broken down into separate functions. You have only one function, `merging`, which does everything: read the temperature file, read the energy file, and then write the output file.

You have good use of `assert` statements to check assumptions, return errors when appropriate, like to make sure that you don't overwrite existing files.

I like that you included a comment to explain what the `index` list was going to contain, when you initialized it as an empty list. The name `index` is far from helpful, but the comment was.

You can go ahead and close this issue now. Thanks!
